@startuml
Spotter -> (Find the missing pets nearby)
Spotter ---> (Comment on a missing entry)
Spotter --> (Send a "PetFound!" message\n to a pet owner with a photo)
Spotter --> (See the comments)
PetOwner --> (See the comments)
PetOwner --> (Create a new \nmissing pet entry)
PetOwner -> (Mark pet as "FOUND")
PetOwner <-- (Receive a notification with \n a photo when the pet is found)
@enduml
